apiVersion: v1
kind: ServiceAccount
metadata:
  name: chess-api-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "c51780fb-e259-46c0-be62-c60a6ebe6cc9"
automountServiceAccountToken: false
